# Generated by Django 5.2 on 2025-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proj",
            name="githuburl",
            field=models.CharField(default="https://github.com", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proj",
            name="contents",
            field=models.CharField(max_length=300),
        ),
    ]
